### ISSUE TITLE
[Question]: Screenshots of badge SVG

### ISSUE THREAD

**Issue by Zo-Bro-23** [Zyplos/discord-readme-badge#4]
Hi @Zyplos,
How did you generate the PNG files in [./src/assets](https://github.com/Zyplos/discord-readme-badge/tree/master/src/assets)? I've made some changes (opened pull request #3), and I want to update the README with the new-style badges. I'm not able to find an easy way to generate PNGs from the generated SVG though (conversion software remove my PFP). Mind sharing how you did it?

Thanks!

**Comment by zyplos** [comment]
Hello,
I imported the SVG generated into Adobe Illustrator and reexported them to PNG to have them in the project's README.
Just updated the README with the new card states, thank you for the contributions!

**Comment by Zo-Bro-23** [comment]
Okay I just wanted to update the README, so I guess that's already done!
