### ISSUE TITLE
Adding game?

### ISSUE THREAD

**Issue by Zo-Bro-23** [Zyplos/discord-readme-badge#7]
Hi, I added ```Youtube music``` to the ```allowlistGames.js``` in my fork, but the application is not reflecting the changes.

![image](https://user-images.githubusercontent.com/62234360/202954802-e36483ef-6f5e-482f-b8bd-7ed43f78c67d.png)

This is what shows in Discord, so ```Youtube music``` is what I should add right? Is there anything else I need to do for the application to show my YouTube Music status? The code you've written handles Spotify differently from how it handles games, but I'm assuming that is because Spotify updates your status through their unique Discord API. YouTube Music just updates the status like VS Code (or other "games") does, since it's just an unofficial client-side application.

**Comment by zyplos** [comment]
Apologies, I hadn't merged your allowList with Youtube Music included. Should be working now.
